// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whtlqimtclodchfdljcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndodGxxaW10Y2xvZGNoZmRsamNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MzI3NDMsImV4cCI6MjA4NjQwODc0M30.wQeww1HOx2rQlmF_RA7rB8BnS8_7hfjVanArHkBY0CQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});